{
 "title": "APF dash",
 "panels": [
  {
   "title": "Reject rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apiserver_flowcontrol_rejected_requests_total[$__rate_interval])",
     "legendFormat": "{{reason}} pl={{priority_level}} fs={{flow_schema}}"
    }
   ]
  },
  {
   "title": "Current Seats in Queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_current_inqueue_seats",
     "legendFormat": "pl={{priority_level}} fs={{flow_schema}}"
    }
   ]
  },
  {
   "title": "Current concurrency limit (seats)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_current_limit_seats",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Current executing seats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_current_executing_seats",
     "legendFormat": "pl={{priority_level}} fs={{flow_schema}}"
    }
   ]
  },
  {
   "title": "Borrowed(Lent) Seats",
   "type": "timeseries",
   "description": "Current concurrency limit - nominal concurrency limit",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_current_limit_seats - apiserver_flowcontrol_nominal_limit_seats",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Seat utilization, 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum without(job, instance) (histogram_quantile(0.95, rate(apiserver_flowcontrol_priority_level_seat_utilization_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_rejected_requests_total",
     "legendFormat": "pl={{priority_level}} fs={{flow_schema}} {{reason}}"
    }
   ]
  },
  {
   "title": "Seat Demand Smoothed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_demand_seats_smoothed",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Nominal concurrency limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_nominal_limit_seats",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Seat Demand High Water Mark",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_demand_seats_high_watermark",
     "legendFormat": "pl={{priority_level}}"
    }
   ]
  },
  {
   "title": "range_interval",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$__rate_interval    ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Server Concurrency Limit (seats)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_nominal_limit_seats)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}