{
 "title": "local-apiserver-jobless",
 "description": "kube-apiserver from local Prometheus endpoint",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "apiserver request rates by APF classification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum without (instance,job,endpoint,service,namespace) (rate(apiserver_flowcontrol_work_estimated_seats_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency, 99th percentile, over last 5 minutes",
   "type": "timeseries",
   "description": "Bucket boundaries at 5, 25, 50, 100, 200 ms; 1, 2, 4, 5, 10, 20, 45, 60 seconds.\nExcluding WATCH and CONNECT.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without(component,endpoint,instance,job,namespace,service) (rate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver request rate by code, resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code,group,resource,subresource) (rate(apiserver_request_total{component=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of k8s API objects in etcd",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg without(job,instance,endpoint,namespace,service) (apiserver_storage_objects{resource!=\"events\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg without(job,instance,endpoint,namespace,service) (apiserver_storage_objects{resource=\"events\"})/20",
     "legendFormat": "events/20"
    }
   ]
  },
  {
   "title": "Request latency, average over last 2 min",
   "type": "timeseries",
   "description": "Excluding WATCH and CONNECT",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(component,endpoint,instance,job,namespace,service) (rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT\"}[2m])) / sum without(component,endpoint,instance,job,namespace,service) (rate(apiserver_request_duration_seconds_count{verb!~\"WATCH|CONNECT\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kube-apiserver request rate by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(apiserver_request_total{component=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver request rate by verb,resource",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (verb,group,resource,subresource) (rate(apiserver_request_total{component=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "persistenvolume* request rates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum without(job,component,endpoint,instance,group,version,service,namespace) (rate(apiserver_request_total{component=\"apiserver\",resource=~\"persistentvolume.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Pod creation and deletion",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(job,namespace,service,component,endpoint,resource,group,version,instance)     (apiserver_request_total{resource=\"pods\",verb=\"POST\",code!~\"4.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without(job,namespace,service,component,endpoint,resource,group,version,instance)     (apiserver_request_total{resource=\"pods\",verb=\"DELETE\",code!~\"4.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}